# .goreleaser.yaml
version: 2
project_name: lanPrint

before:
  hooks:
    - go mod tidy

builds:
  - id: lanPrint
    main: ./cmd/lanPrint
    binary: lanPrint
    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: arm
        env:
          - CC=arm-linux-gnueabihf-gcc
    ignore:
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
      - "{{ if eq .Os \"windows\" }}-H=windowsgui{{ end }}"

archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_{{ if eq .Os "darwin" }}Mac{{ else }}{{ title .Os }}{{ end }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: kaiyuan
    name: lanPrint

nfpms:
  - id: lanPrint
    package_name: lanprint
    vendor: lanPrint
    homepage: https://github.com/kaiyuan/lanPrint
    maintainer: kaiyuan <kaiyuan@boxks.com>
    description: Cross-platform printing gateway
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/lanprint/copyright
      - src: README.md
        dst: /usr/share/doc/lanprint/README.md
